backend:
  name: git-gateway
  branch: main

media_folder: "public/assets"
public_folder: "/assets"

collections:
  - name: "releases"
    label: "Releases"
    folder: "releases"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", default: ["releases"] }

  - name: "radio"
    label: "Radio"
    folder: "radio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "External URL", name: "external_url", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["radio"] }

  - name: "read"
    label: "Read"
    folder: "read"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "External URL", name: "external_url", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["read"] }

  - name: "live"
    label: "Live"
    folder: "live"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", default: ["live"] }

  - name: "watch"
    label: "Watch"
    folder: "watch"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "External URL", name: "external_url", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["watch"] }
