
backend:
  name: git-gateway
  branch: main

media_folder: "public/assets"
public_folder: "/public/assets"

collections:
  - name: "releases"
    label: "Releases"
    folder: "releases"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "release.njk" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Bandcamp Link", name: "bandcamp", widget: "string" }
