backend:
  name: git-gateway
  branch: main

media_folder: "public/assets"
public_folder: "/assets"

collections:
  - name: "release"
    label: "Releases"
    folder: "releases"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Bandcamp Embed (iframe)", name: "bandcamp", widget: "text", required: false }

  - name: "radio"
    label: "Radio"
    folder: "radio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "External Link", name: "external", widget: "string" }

  - name: "read"
    label: "Read"
    folder: "read"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "External Link", name: "external", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: "live"
    label: "Live"
    folder: "live"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "watch"
    label: "Watch"
    folder: "watch"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Video Embed (iframe)", name: "video", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
